version: '3'
services:

  multicast-nmea:
    build: .
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MCAST_GRP=239.192.0.3
      - MCAST_PORT=60003
      - MQTT_TOPIC_RAW=CROWSNEST/SEAHORSE/GNSS/0/RAW
      - MQTT_TOPIC_JSONCROWSNEST/SEAHORSE/GNSS/0/JSON
